import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { ReactNode } from 'react';
import Header from '../header/Header';

const ADMIN_ROUTE = '/admin';

export default function RootLayout({ children }: { children: ReactNode }): ReactNode {
  const { pathname } = useRouter();
  const isCMSView = pathname.includes(ADMIN_ROUTE);

  if (isCMSView) return children;

  return (
    <>
      <Head>
        <title>Enciende Tu Poder</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <Header />
        {children}
      </main>

      <footer></footer>
    </>
  );
}
