import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React, { ReactNode } from 'react';
import Header from '../header/Header';

const ADMIN_ROUTE = '/admin';

export default function RootLayout({ children }: { children: ReactNode }): JSX.Element {
  const { pathname } = useRouter();
  const isCMSView = pathname.includes(ADMIN_ROUTE);

  if (isCMSView) return <>{children}</>;

  return (
    <>
      <Head>
        <title>Enciende Tu Poder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        {children}
      </main>

      <footer></footer>
    </>
  );
}
